version: '3.8'

services:
  postgres-db:
    image: postgres:16.3
    restart: always
    container_name: postgres-db
    ports:
      - 5600:5432
    environment:
      POSTGRES_DB: my_django
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - app-network

  web:
    build: ./backend/
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
      - redis
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-e3-dfc5$67!z!scs=mex6xmq=5l@1u4g)ckajac+dhh)jl*91o
      - DJANGO_SETTINGS_MODULE=core.settings
      - POSTGRES_DB=my_django
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
