# Generated by Django 5.0.6 on 2024-08-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatconfirmation',
            old_name='message',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='data',
        ),
    ]
