# Generated by Django 5.0.6 on 2024-08-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_id',
            field=models.UUIDField(),
        ),
    ]
