# Generated by Django 5.0.6 on 2024-08-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_alter_chatmessage_receiver_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_id',
            field=models.CharField(max_length=36),
        ),
    ]
