POST http://127.0.0.1:8000/register/
Content-Type: application/json

{"username": "user2", "password": "Pass1234!", "email": "user1@test.test"}

###

POST http://127.0.0.1:8000/login/
Content-Type: application/json

{"username": "user2", "password": "Pass1234!"}

### 

POST http://127.0.0.1:8000/logout/
Content-Type: application/json
Authorization: Token 028acc1b37bcac6158225fbfb446cebf8edafe01

{}
### 

GET http://127.0.0.1:8000/public/
Content-Type: application/json

{}
### 

GET http://127.0.0.1:8000/private/
Content-Type: application/json
Authorization: Bearer <>


{}
### 

POST http://127.0.0.1:8000/token/refresh/
Content-Type: application/json

{
    "refresh": <>
}