POST http://192.168.214.206:8000/login/
Content-Type: application/json

{"username": "user3", "password1": "Pass1234!", "password2": "Pass1234!", "email": "user3@test.test"}

###
POST http://192.168.214.206:8000/register/
Content-Type: application/json

{"username": "user33", "password": "Pass1234!", "email": "user33@test.test"}

###
GET http://192.168.214.206:8000/private
Content-Type: application/json

{"username": "user3", "password1": "Pass1234!", "password2": "Pass1234!", "email": "user3@test.test"}

###
GET http://192.168.214.206:8000/public
Content-Type: application/json

{"username": "user3", "password1": "Pass1234!", "password2": "Pass1234!", "email": "user3@test.test"}

###
POST http://192.168.214.206:8000/dj-rest-auth/login/
Content-Type: application/json

{
  "username": "NewestUser1",
  "password": "test123!@#"
}

###
POST http://192.168.214.206:8000/dj-rest-auth/registration/
Content-Type: application/json

{
  "username": "NewestUser21",
  "email": "NewestUser@test.com",
  "password1": "test123!@#",
  "password2": "test123!@#"
}


###
POST http://192.168.214.206:8000/dj-rest-auth/logout/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyMjI4NDMwMiwiaWF0IjoxNzIyMTk3OTAyLCJqdGkiOiJhNDFiMDJkMDM3YzY0YzQ5OTk0YjYwYWZhODVhOWI1ZCIsInVzZXJfaWQiOjJ9.IsXNEBmPmUnilS48T0ckdpGjX26PuVUU_kkNdQ592C0"
}

###
POST http://192.168.214.206:8000/dj-rest-auth/password/reset/
Content-Type: application/json

{
  "email": "NewestUser@test.com"
}
###
GET http://192.168.214.206:8000/dj-rest-auth/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyMjQwOTQ3LCJpYXQiOjE3MjIyMzk3NDcsImp0aSI6IjVkNWM3NDYyNTNkMTRiZjg4MjM2MTZmYWI0YTdmM2UxIiwidXNlcl9pZCI6IjQxMGU4MGU5LTk3ODMtNDlhOC04ZjgyLTEyNzIwMmQzNDZmOCJ9.krLH1_uq4dvjWRDH7ZtWaMi_w5IsrAxF9TX2vwwwZic

{}
###
PATCH http://192.168.214.206:8000/dj-rest-auth/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyMjAzMTMwLCJpYXQiOjE3MjIyMDI4MzAsImp0aSI6IjFkZDc4ZDdiNTZiYTQ5N2ZhZTllMGI1MzRkMjQ2NGMxIiwidXNlcl9pZCI6ImI5YWIyMjc2LTcxZTgtNGJiNC1iOGFlLTc1ZWYzMmZiM2EwOCJ9.ndboMhMEC5mvOlHKvS74e8HnTV_JKwIu5OQFu4fZpTs

{"first_name": "asd","last_name": "dsa"}
###
GET http://192.168.214.206:8000/api/v1/user/profile/imageURL/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyMzg1MDUwLCJpYXQiOjE3MjIzODM4NTAsImp0aSI6IjM4ZTkxOTQxNzIzZjQ1NjM4ZWFhMzkxNTBiZjZkNmRmIiwidXNlcl9pZCI6Ijk1MzMyYWRjLWM3NzctNGM1MS04ODdhLWI5NzJlNDY4OWJlMCIsInVzZXIiOnsiaWQiOiI5NTMzMmFkYy1jNzc3LTRjNTEtODg3YS1iOTcyZTQ2ODliZTAiLCJ1c2VybmFtZSI6InBhYmxvMSIsImVtYWlsIjoicGFibG9AdGVzdC5jb20iLCJpbWFnZVVSTCI6IiIsImRldmljZV9pZCI6InAxIiwiZmlyc3RfbmFtZSI6IiIsImxhc3RfbmFtZSI6IiIsImlzX3N0YWZmIjpmYWxzZX19.I47boB0GJ2uXBk4IaV_ZABIUrCCpDQiz8gow7D66ERc

{"imageURL": ""}
###
POST http://192.168.214.206:8000/check-email/
Content-Type: application/json

{
    "email": "NewestUser@test.com"
}
