# Generated by Django 5.0.6 on 2024-07-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='imageURL',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
