# Generated by Django 5.0.6 on 2024-07-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_customuser_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device_ids',
            field=models.JSONField(default=list),
        ),
    ]
